### PR TITLE
improve debugging of wire decode errors

### PR DESCRIPTION
**Pull request by andreas-ibm**
Hello, I couldn't see the actual error, just a rather unhelpful "Wire format is invalid" message.  By adding the exception I can see what's actually wrong!

### CODE REVIEW

**Comment by andreas-ibm** [comment]
I have added a second change.
The .proto files I use have a dependency on other .proto files for parts of their messages. 
By changing the config to allow for comma-separated values I can now specify all of them and get my messages decoded.

**Comment by w4tsn** [comment]
Hey there, sorry for letting you wait. I've not received notification for this. Let me go through it and I'll let you know what I think :)

**Comment by andreas-ibm** [comment]
Thanks, happy to make changes if needed

**Comment by w4tsn** [comment]
Thanks for the MR! Much appreciated :)

**Pull request merged**
